### ISSUE TITLE
Importing a module not specified in package.json

### ISSUE THREAD

**Issue by yads** [embroider-build/ember-auto-import#353] opened 2021-02-23 16:22 UTC
Importing d3, imports all of its sub modules, like d3-scale, d3-select, etc. However, the only way to get ember-auto-import to import these sub modules is to explicitly specify them in the package.json. Is there a way to have ember-auto-import allow importing of packages that may not be explicitly specified in package.json?

EDIT: looks like it's due to this code block https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/package.ts#L226
Is there any appetite for having an explicit `include` list, similar to `exclude` that would allow certain packages to be included even if they are not explicitly defined in package.json? (AFAIK resolve-package-path will find these packages)

**Comment by ef4** [comment] 2021-02-24 23:06
Importing things you don't directly depend on only works by accident because of certain unreliable optimizations in NPM & yarn 1. It is very much discouraged.

**Comment by yads** [comment] 2021-02-25 14:54
I understand what you're saying, you don't want people to try to import random sub-dependencies or sub-sub-dependencies and expect things to work. However, I think d3 is a real use case https://github.com/d3/d3. Their own docs specify that you install d3 and then you either import the entirety of d3 or the individual modules. To get d3 to work with ember-auto-import my options are: import the entirety of d3: `import * as d3 from 'd3'` (which has a bundle size impact) or mangle my package.json to trick ember-auto-import into importing the sub dependencies:

```json
    "d3": "^6.5.0",
    "d3-array": "2",
    "d3-axis": "2",
    "d3-color": "2",
    "d3-ease": "2",
```

I'm not saying the dependency check should be removed entirely, but perhaps an option to allow specifying allowed sub-modules would be an acceptable compromise? I can get a PR for this, if this is something you'd be interested in supporting.

**Comment by ef4** [comment] 2021-02-25 15:39
I understand their docs say to do that, but they're just wrong. Both yarn 2 and pnpm will break if you use this strategy. It locks you into an accidental implementation detail of npm (and yarn 1) -- a detail that is extremely problematic and causes major correctness and performance problems. I predict that even NPM is going to eventually be forced to move to a stricter mode that breaks this.

Avoiding this problem doesn't require any hacks. If you really want to import from `d3-array`, then depend on `d3-array`. Drop the `d3` dependency entirely. Put into package.json exactly the set of packages that your app uses. This isn't mangling your package.json, this is using your package.json as intended. In the same way that directly importing the sub-packages helps your bundle size, this will help your node_modules size too -- why install libraries you aren't using?

I realize it's nice to have a meta package that helps you curate exactly which versions of the subpackages will be used. But to do that, the meta package needs to declare `peerDependencies`, not `dependencies`, and up until very recently that didn't actually help the user much because all peerDeps had to be hand-managed (npm 7 has supposedly fixed this but I haven't dived deep into trying it).

For cases where you really need to subvert package resolution, we already offer `alias`. Something like this would like you import from `d3-scale` without depending on it directly:

```js
let app = new EmberApp(defaults, {
  autoImport: {
    alias: {
      'd3-scale': './node_modules/d3-scale/dist/d3-scale.js'
    }
  }
});

```

**Comment by knownasilya** [comment] 2021-03-04 18:32
Semi-related, but I added d3-zoom to my package.json in an addon and getting missing module error. The addon was freshly generated today. Any thoughts?

**Comment by bendemboski** [comment] 2021-03-07 18:06
@knownasilya the issue with that addon is that `ember-auto-import` is a `devDependency` -- see [addon instructions](https://github.com/ef4/ember-auto-import#usage-from-addons)

**Comment by knownasilya** [comment] 2021-03-08 15:51
That resolved the issue. I wonder if a better error message would have been possible. Like suggesting moving it to dependencies if in an addon?

**Comment by ef4** [comment] 2021-03-08 17:34
We can probably add that better error message. But it would need to be
triggered by seeing a devDependency import in the addon code, and not
triggered by seeing a devDependency import in the dummy app.

**Comment by bendemboski** [comment] 2021-03-08 17:57
Maybe this would be better implemented as a linting rule?

**Comment by ef4** [comment] 2021-03-08 19:15
That's a good point, and we can probably use an existing eslint plugin like https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

But the challenge is, most ember apps have a ton of imports that aren't real packages, and all of those would trigger this kind of rule.

**Comment by bendemboski** [comment] 2021-03-08 20:10
Yeah, I was picturing something more along the lines of [no-unpublished-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md) -- in Ember finding "extraneous dependencies" seems very challenging, but perhaps targeting dependencies that are:

1. In addons (rule doesn't apply to apps)
2. Imported from `/addon` or `/app` or `/addon-test-support` (maybe others?)
2. Found in `node_modules`
3. In `devDependencies` instead of `dependencies`

I'm not sure if the whole plan is feasible/worthwhile, but I'm thinking that if it is, it's probably better as a linting rule than some code living in `ember-auto-import`.

**Comment by jamesarosen** [comment] 2023-09-06 20:38
I wanted the `d3` meta-package to manage all the sub-package versions, so I declared a version-specific dependency on it plus a loose dependency on each sub-package that I use:

```json5
// package.json
dependencies: {
  "d3": "^5.7.0",
  "d3-array": "*",
  "d3-axis": "*",
  // etc.
}
```

I didn't need `alias` configuration with this.

**Comment by void-mAlex** [comment] 2023-09-06 22:10
closing as issue has answer

**Closed by void-mAlex** 2023-09-06 22:10 UTC

**Comment by yads** [comment] 2023-11-01 18:51
So I tried the approach suggested by @jamesarosen and yarn seemed to use the loose dependency for resolution, i.e. even though [d3@6.5.0](https://github.com/d3/d3/blob/v6.5.0/package.json) specifies d3-array@2, yarn decided to install the latest d3-array which was version 3.2.4. Am I doing something wrong? I have this in `dependencies`:
```
  "dependencies": {
    "d3": "^6.5.0",
    "d3-array": "*",
    "d3-axis": "*",
    "d3-color": "*",
    "d3-ease": "*",
    "d3-force": "*",
    "d3-hierarchy": "*",
    "d3-interpolate": "*",
    "d3-scale": "*",
    "d3-selection": "*",
    "d3-shape": "*",
    "d3-time": "*",
    "d3-transition": "*"
  },
```
and in `devDependencies` as well
